version: '3.8'

services:
  # etcd 服务发现
  etcd:
    image: quay.io/coreos/etcd:v3.5.10
    container_name: grpc-kit-etcd
    command:
      - /usr/local/bin/etcd
      - --name=etcd0
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd0=http://0.0.0.0:2380
      - --initial-cluster-token=tkn
      - --initial-cluster-state=new
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd-data:/etcd-data

  # Prometheus 监控
  prometheus:
    image: prom/prometheus:latest
    container_name: grpc-kit-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

  # Grafana 可视化
  grafana:
    image: grafana/grafana:latest
    container_name: grpc-kit-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources

  # gRPC 服务示例
  grpc-service:
    build: .
    container_name: grpc-kit-service
    ports:
      - "8080:8080"
      - "9091:9090"
      - "8081:8081"
    environment:
      - GRPC_KIT_DISCOVERY_ENDPOINTS=etcd:2379
      - GRPC_KIT_SERVER_HOST=0.0.0.0
    depends_on:
      - etcd
    volumes:
      - ./config:/app/config

volumes:
  etcd-data:
  grafana-data: