global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # gRPC 服务监控
  - job_name: 'grpc-kit'
    static_configs:
      - targets: ['grpc-service:8081']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # etcd 监控
  - job_name: 'etcd'
    static_configs:
      - targets: ['etcd:2379']
    metrics_path: '/metrics'