server:
  host: "0.0.0.0"
  port: 8080
  grpc_port: 9090

grpc:
  server:
    max_recv_msg_size: 4194304  # 4MB
    max_send_msg_size: 4194304  # 4MB
  client:
    timeout: 30
    max_retries: 3
    load_balancing: "round_robin"

discovery:
  type: "etcd"
  endpoints:
    - "localhost:2379"
  namespace: "/grpc-kit"

logging:
  level: "info"
  format: "json"

tls:
  enabled: false

metrics:
  enabled: true
  port: 8081
  path: "/metrics"

# 自动注册配置
auto_register:
  enabled: true                     # 启用自动注册
  scan_dirs:                       # 扫描目录列表
    - "./services"
  patterns:                        # 文件匹配模式
    - "*.go"
  excludes:                        # 排除模式
    - "*_test.go"
    - "*_mock.go"
  service_name: ""                 # 服务名称模式（可选）